require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccountBalancesController do

  # This should return the minimal set of attributes required to create a valid
  # AccountBalance. As you add validations to AccountBalance, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccountBalancesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all account_balances as @account_balances" do
      account_balance = AccountBalance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:account_balances).should eq([account_balance])
    end
  end

  describe "GET show" do
    it "assigns the requested account_balance as @account_balance" do
      account_balance = AccountBalance.create! valid_attributes
      get :show, {:id => account_balance.to_param}, valid_session
      assigns(:account_balance).should eq(account_balance)
    end
  end

  describe "GET new" do
    it "assigns a new account_balance as @account_balance" do
      get :new, {}, valid_session
      assigns(:account_balance).should be_a_new(AccountBalance)
    end
  end

  describe "GET edit" do
    it "assigns the requested account_balance as @account_balance" do
      account_balance = AccountBalance.create! valid_attributes
      get :edit, {:id => account_balance.to_param}, valid_session
      assigns(:account_balance).should eq(account_balance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AccountBalance" do
        expect {
          post :create, {:account_balance => valid_attributes}, valid_session
        }.to change(AccountBalance, :count).by(1)
      end

      it "assigns a newly created account_balance as @account_balance" do
        post :create, {:account_balance => valid_attributes}, valid_session
        assigns(:account_balance).should be_a(AccountBalance)
        assigns(:account_balance).should be_persisted
      end

      it "redirects to the created account_balance" do
        post :create, {:account_balance => valid_attributes}, valid_session
        response.should redirect_to(AccountBalance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved account_balance as @account_balance" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountBalance.any_instance.stub(:save).and_return(false)
        post :create, {:account_balance => {}}, valid_session
        assigns(:account_balance).should be_a_new(AccountBalance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AccountBalance.any_instance.stub(:save).and_return(false)
        post :create, {:account_balance => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested account_balance" do
        account_balance = AccountBalance.create! valid_attributes
        # Assuming there are no other account_balances in the database, this
        # specifies that the AccountBalance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AccountBalance.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => account_balance.to_param, :account_balance => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested account_balance as @account_balance" do
        account_balance = AccountBalance.create! valid_attributes
        put :update, {:id => account_balance.to_param, :account_balance => valid_attributes}, valid_session
        assigns(:account_balance).should eq(account_balance)
      end

      it "redirects to the account_balance" do
        account_balance = AccountBalance.create! valid_attributes
        put :update, {:id => account_balance.to_param, :account_balance => valid_attributes}, valid_session
        response.should redirect_to(account_balance)
      end
    end

    describe "with invalid params" do
      it "assigns the account_balance as @account_balance" do
        account_balance = AccountBalance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountBalance.any_instance.stub(:save).and_return(false)
        put :update, {:id => account_balance.to_param, :account_balance => {}}, valid_session
        assigns(:account_balance).should eq(account_balance)
      end

      it "re-renders the 'edit' template" do
        account_balance = AccountBalance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AccountBalance.any_instance.stub(:save).and_return(false)
        put :update, {:id => account_balance.to_param, :account_balance => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested account_balance" do
      account_balance = AccountBalance.create! valid_attributes
      expect {
        delete :destroy, {:id => account_balance.to_param}, valid_session
      }.to change(AccountBalance, :count).by(-1)
    end

    it "redirects to the account_balances list" do
      account_balance = AccountBalance.create! valid_attributes
      delete :destroy, {:id => account_balance.to_param}, valid_session
      response.should redirect_to(account_balances_url)
    end
  end

end
